// Generated by CoffeeScript 1.11.1
var convex_hull, draw, input_points, keyPressed, mousePressed, setup;

input_points = [new Point(300, 200), new Point(200, 100), new Point(100, 300), new Point(200, 400), new Point(100, 400), new Point(240, 320), new Point(280, 150)];

convex_hull = [];

setup = function() {
  createCanvas(640, 480);
  return fill('black');
};

draw = function() {
  var i, j, k, len, p_i, ref;
  background(200);
  for (j = 0, len = input_points.length; j < len; j++) {
    p_i = input_points[j];
    ellipse(p_i.x, p_i.y, 4, 4);
  }
  if (convex_hull.length > 2) {
    for (i = k = 0, ref = convex_hull.length - 2; 0 <= ref ? k <= ref : k >= ref; i = 0 <= ref ? ++k : --k) {
      line(convex_hull[i].x, convex_hull[i].y, convex_hull[i + 1].x, convex_hull[i + 1].y);
    }
    return line(convex_hull[convex_hull.length - 1].x, convex_hull[convex_hull.length - 1].y, convex_hull[0].x, convex_hull[0].y);
  }
};

mousePressed = function() {
  return input_points.push(new Point(mouseX, mouseY));
};

keyPressed = function() {
  convex_hull = convex_hull_graham_scan(input_points);
  return console.log("size: ", convex_hull.length, "\nhull: ", convex_hull, "\n");
};
