// Generated by CoffeeScript 1.11.1
var draw, input_anchor, input_points, keyPressed, mousePressed, setup;

input_points = [new Point(100, 10), new Point(300, 200), new Point(423, 200), new Point(100, 300), new Point(500, 120), new Point(200, 320), new Point(50, 40), new Point(50, 350), new Point(150, 350), new Point(220, 400), new Point(240, 320), new Point(280, 450)];

input_anchor = new Point(320, 240);

setup = function() {
  createCanvas(640, 480);
  return fill('black');
};

draw = function() {
  var i, j, k, len, p_i, ref, ref1, results;
  background(200);
  line(0, 240, 640, 240);
  line(320, 0, 320, 480);
  fill("green");
  stroke("green");
  ellipse(0, 0, 6, 6);
  ellipse(input_anchor.x, input_anchor.y, 10, 10);
  ellipse(input_points[0].x, input_points[0].y, 6, 6);
  stroke(51);
  fill(51);
  ref = input_points.slice(1);
  for (j = 0, len = ref.length; j < len; j++) {
    p_i = ref[j];
    ellipse(p_i.x, p_i.y, 4, 4);
  }
  if (input_points.length > 2) {
    results = [];
    for (i = k = 0, ref1 = input_points.length - 2; 0 <= ref1 ? k <= ref1 : k >= ref1; i = 0 <= ref1 ? ++k : --k) {
      results.push(line(input_points[i].x, input_points[i].y, input_points[i + 1].x, input_points[i + 1].y));
    }
    return results;
  }
};

mousePressed = function() {
  return input_points.push(new Point(mouseX, mouseY));
};

keyPressed = function() {
  var anchor, ccw;
  console.log("\n input: ", input_points);
  radial_sort(input_points, anchor = null, ccw = true);
  return console.log("sorted: ", input_points, "\n");
};
