// Generated by CoffeeScript 1.12.3
var binary_search;

binary_search = function(points, comparator, arg) {
  var force_return, ref, start, stop;
  ref = arg != null ? arg : {}, force_return = ref.force_return, start = ref.start, stop = ref.stop;
  if (start == null) {
    start = 0;
  }
  if (stop == null) {
    stop = length(points) - 1;
  }
  while (start < stop) {
    start += 1;
  }
  return console.log("done");
};

binary_search(0/0, 0/0);
