// Generated by CoffeeScript 1.12.3
var compute_k_level, h, w;

w = 640;

h = 480;

compute_k_level = function(input_lines, k) {
  var best_so_far, current_line, first_intersection, i, intersections, j, k_level_points, l, l_i, last_point, len, lines, ref, second_to_last_point, still_in_canvas, x_i, y_i;
  console.log(input_lines);
  lines = input_lines.slice();
  k_level_points = [];
  lines.sort(function(a, b) {
    if (a.q > b.q) {
      return 1;
    } else if (a.q < b.q) {
      return -1;
    } else {
      return 0;
    }
  });
  console.log("\n\nSORTED:\n" + lines);
  current_line = lines[k - 1];
  k_level_points.push(current_line.start);
  still_in_canvas = true;
  while (still_in_canvas) {
    intersections = [];
    for (j = 0, len = lines.length; j < len; j++) {
      l_i = lines[j];
      if (current_line.m === l_i.m) {
        intersections.push(new Point(Number.POSITIVE_INFINITY, Number.POSITIVE_INFINITY));
      } else {
        x_i = (l_i.q - current_line.q) / (current_line.m - l_i.m);
        y_i = l_i.m * x_i + l_i.q;
        intersections.push(new Point(x_i, y_i));
      }
    }
    first_intersection = 0;
    best_so_far = Number.POSITIVE_INFINITY;
    for (i = l = 0, ref = intersections.length - 1; 0 <= ref ? l <= ref : l >= ref; i = 0 <= ref ? ++l : --l) {
      if (intersections[i].x > k_level_points[k_level_points.length - 1].x) {
        if (intersections[i].x < best_so_far) {
          first_intersection = i;
          best_so_far = intersections[i].x;
        }
      }
    }
    k_level_points.push(intersections[first_intersection]);
    current_line = lines[first_intersection];
    if (k_level_points[k_level_points.length - 1].x > w) {
      still_in_canvas = false;
      last_point = k_level_points[k_level_points.length - 1];
      second_to_last_point = k_level_points[k_level_points.length - 2];
      k_level_points.splice(-1, 1);
      k_level_points.push(new Point(w, ((last_point.y - second_to_last_point.y) / (last_point.x - second_to_last_point.x)) * (w - second_to_last_point.x) + second_to_last_point.y));
    }
    if (k_level_points[k_level_points.length - 1].y > h) {
      still_in_canvas = false;
      last_point = k_level_points[k_level_points.length - 1];
      second_to_last_point = k_level_points[k_level_points.length - 2];
      k_level_points.splice(-1, 1);
      k_level_points.push(new Point(((-last_point.x + second_to_last_point.x) / (last_point.y - second_to_last_point.y)) * (h - last_point.y) + second_to_last_point.x, h));
    }
    if (k_level_points[k_level_points.length - 1].y < 0) {
      still_in_canvas = false;
      last_point = k_level_points[k_level_points.length - 1];
      second_to_last_point = k_level_points[k_level_points.length - 2];
      k_level_points.splice(-1, 1);
      k_level_points.push(new Point(second_to_last_point.x, h));
    }
  }
  return k_level_points;
};
