// Generated by CoffeeScript 1.12.3
var S, a, b, compute_k_sets, k, k_sets;

a = new Point(2, 3);

b = new KSetElem(4, 5, 0.1);

console.log(_.isEqual(a, a));

console.log(b);

console.log(squared_distance(a, new Point(2, 3)));

compute_k_sets = function(S, arg) {
  var k, k_sets, n_points;
  k = (arg != null ? arg : {}).k;
  if (k == null) {
    k = 1;
  }
  n_points = S.length;
  return k_sets = [];
};

S = [new Point(1, 3), new Point(4, 2), new Point(8, 2), new Point(9, 4), new Point(2, 5), new Point(4, 3), new Point(6, 4)];

console.log(S);

k = 1;

k_sets = compute_k_sets(S, k);

console.log(k_sets);
