// Generated by CoffeeScript 1.11.1
var cell, cells, draw, draw_poly, drawing_points_done, h, input_points, inter, keyPressed, lines, mousePressed, query_point, res, setup, w;

query_point = false;

drawing_points_done = false;

lines = false;

inter = false;

res = false;

w = 1200;

h = 800;

input_points = [];

cell = false;

cells = false;

setup = function() {
  createCanvas(w, h);
  return fill('black');
};

draw = function() {
  var i, j, k, len, p, ref, results;
  background(230);
  fill("black");
  stroke("black");
  for (j = 0, len = input_points.length; j < len; j++) {
    p = input_points[j];
    ellipse(p.x, p.y, 10, 10);
  }
  if (cells) {
    results = [];
    for (i = k = 0, ref = cells.length; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
      results.push(draw_poly(radial_sort(cells[i], input_points[i])));
    }
    return results;
  }
};

mousePressed = function() {
  if (!drawing_points_done) {
    return input_points.push(new Point(mouseX, mouseY));
  } else {
    return cells = find_cells(input_points);
  }
};

keyPressed = function() {
  drawing_points_done = true;
  return cells = find_cells(input_points);
};

draw_poly = function(points) {
  var j, len, p_i;
  fill(123, 23, 76, 40);
  beginShape();
  for (j = 0, len = points.length; j < len; j++) {
    p_i = points[j];
    vertex(p_i.x, p_i.y);
  }
  return endShape(CLOSE);
};
