// Generated by CoffeeScript 1.11.1
var cell, draw, draw_poly, drawing_points_done, h, input_points, inter, lines, mousePressed, r1, r2, r3, res, setup, w,
  modulo = function(a, b) { return (+a % (b = +b) + b) % b; };

drawing_points_done = false;

w = 1200;

h = 800;

r1 = Math.random();

r2 = Math.random();

r3 = Math.random();

input_points = [];

cell = false;

lines = false;

res = false;

inter = false;

setup = function() {
  createCanvas(w, h);
  return fill('black');
};

draw = function() {
  var i, j, l, len, len1, p;
  background(230);
  fill("black");
  stroke("black");
  for (i = 0, len = input_points.length; i < len; i++) {
    p = input_points[i];
    ellipse(p.x, p.y, 10, 10);
  }
  if (cell) {
    fill("red");
    stroke("red");
    for (j = 0, len1 = res.length; j < len1; j++) {
      l = res[j];
      ellipse(l[0].x, l[0].y, 14, 14);
      ellipse(l[1].x, l[1].y, 14, 14);
      line(l[0].x, l[0].y, l[1].x, l[1].y);
    }
    return draw_poly(radial_sort(cell, input_points[input_points.length - 1]));
  }
};

mousePressed = function() {
  var ref;
  input_points.push(new Point(mouseX, mouseY));
  if (input_points.length > 1) {
    return ref = find_cell(input_points, input_points[input_points.length - 1]), lines = ref[0], res = ref[1], inter = ref[2], cell = ref[3], ref;
  }
};

draw_poly = function(points) {
  var coord, i, j, len, len1, p, p_i;
  coord = 0;
  for (i = 0, len = points.length; i < len; i++) {
    p = points[i];
    coord += p.x + p.y;
  }
  fill(modulo(coord * r1, 256), modulo(coord * r2, 256), modulo(coord * r3, 256), 40);
  beginShape();
  for (j = 0, len1 = points.length; j < len1; j++) {
    p_i = points[j];
    vertex(p_i.x, p_i.y);
  }
  return endShape(CLOSE);
};
