// Generated by CoffeeScript 1.12.3
var draw, input_points, k, keyPressed, mouseWheel, setup, zonoid;

input_points = [new Point(100, 10), new Point(300, 200), new Point(423, 200), new Point(100, 300), new Point(500, 120), new Point(200, 320), new Point(50, 40), new Point(50, 350), new Point(150, 350), new Point(220, 400), new Point(240, 320), new Point(280, 450)];

k = 1;

zonoid = [];

setup = function() {
  createCanvas(640, 480);
  return fill('black');
};

draw = function() {
  var i, j, len, len1, p_i, results, z_i;
  background(200);
  line(0, 240, 640, 240);
  line(320, 0, 320, 480);
  fill("black");
  stroke("black");
  for (i = 0, len = input_points.length; i < len; i++) {
    p_i = input_points[i];
    ellipse(p_i.x, p_i.y, 4, 4);
  }
  fill("green");
  stroke("green");
  results = [];
  for (j = 0, len1 = zonoid.length; j < len1; j++) {
    z_i = zonoid[j];
    results.push(ellipse(z_i.x, z_i.y, 10, 10));
  }
  return results;
};

keyPressed = function() {
  if (keyCode === LEFT_ARROW) {
    k -= 1;
  } else if (keyCode === RIGHT_ARROW) {
    k += 1;
  }
  if (k < 1) {
    k = 1;
  }
  if (k > input_points.length) {
    k = input_points.length;
  }
  return zonoid = compute_zonoid(input_points, {
    k: k
  });
};

mouseWheel = function(event) {
  if (event.delta > 0) {
    k -= 0.1;
  } else if (event.delta < 0) {
    k += 0.1;
  }
  if (k < 1) {
    k = 1;
  }
  if (k > input_points.length) {
    k = input_points.length;
  }
  return zonoid = compute_zonoid(input_points, {
    k: k
  });
};
