// Generated by CoffeeScript 1.12.3
var default_color, draw, dual_lines, h, input_points, num_input_points, scale_factor, setup, w;

input_points = [new Point(2, -2), new Point(-0.8, 4.2), new Point(1, 3), new Point(0.5, -1), new Point(0.4, 1.2), new Point(-0.2, 2.2), new Point(1.4, 0.3), new Point(-0.3, 4.8)];

default_color = [121, 204, 147, 40];

num_input_points = 15;

scale_factor = 100;

h = 480;

w = 640;

dual_lines = [];

setup = function() {
  var i, len, p, results;
  createCanvas(w, h);
  fill('red');
  frameRate(10);
  results = [];
  for (i = 0, len = input_points.length; i < len; i++) {
    p = input_points[i];
    results.push(dual_lines.push(create_line_from_m_q(p.x, p.y * scale_factor)));
  }
  return results;
};

draw = function() {
  var i, l, len, results;
  background(255, 251, 234);
  fill("black");
  stroke("black");
  results = [];
  for (i = 0, len = dual_lines.length; i < len; i++) {
    l = dual_lines[i];
    ellipse(l.start.x, l.start.y, 10, 10);
    ellipse(l.end.x, l.end.y, 10, 10);
    results.push(line(l.start.x, l.start.y, l.end.x, l.end.y));
  }
  return results;
};
