// Generated by CoffeeScript 1.11.1
var cells, draw, draw_poly, drawing_points_done, edges, h, input_points, inter, keyPressed, lines, mousePressed, query_point, r1, r2, r3, res, setup, w,
  modulo = function(a, b) { return (+a % (b = +b) + b) % b; };

query_point = false;

drawing_points_done = false;

lines = false;

inter = false;

res = false;

w = 1200;

h = 800;

input_points = [];

edges = false;

cells = false;

r1 = Math.random();

r2 = Math.random();

r3 = Math.random();

setup = function() {
  createCanvas(w, h);
  return fill('black');
};

draw = function() {
  var e, i, j, k, l, len, len1, p, ref, results;
  background(230);
  fill(Math.floor(r1 * 256), Math.floor(r2 * 256), Math.floor(r3 * 256));
  stroke(Math.floor(r1 * 256), Math.floor(r2 * 256), Math.floor(r3 * 256));
  if (edges) {
    for (j = 0, len = edges.length; j < len; j++) {
      e = edges[j];
      line(e[0].x, e[0].y, e[1].x, e[1].y);
    }
  }
  fill("black");
  stroke("black");
  for (k = 0, len1 = input_points.length; k < len1; k++) {
    p = input_points[k];
    ellipse(p.x, p.y, 10, 10);
  }
  if (cells) {
    results = [];
    for (i = l = 0, ref = cells.length; 0 <= ref ? l < ref : l > ref; i = 0 <= ref ? ++l : --l) {
      results.push(draw_poly(radial_sort(cells[i], input_points[i])));
    }
    return results;
  }
};

mousePressed = function() {
  return input_points.push(new Point(mouseX, mouseY));
};

keyPressed = function() {
  drawing_points_done = true;
  cells = find_cells(input_points);
  return edges = delaunay_triangulation(input_points);
};

draw_poly = function(points) {
  var coord, j, k, len, len1, p, p_i;
  coord = 0;
  for (j = 0, len = points.length; j < len; j++) {
    p = points[j];
    coord += p.x + p.y;
  }
  fill(modulo(coord * r1, 256), modulo(coord * r2, 256), modulo(coord * r3, 256), 40);
  beginShape();
  for (k = 0, len1 = points.length; k < len1; k++) {
    p_i = points[k];
    vertex(p_i.x, p_i.y);
  }
  return endShape(CLOSE);
};
